// Code generated by scripts/generate-portable-artifact-diagnostics from
// contracts/fixtures/portable-artifact/diagnostics-v1.json; DO NOT EDIT.
// Source contract SHA-256: 3c948169592980b1e85d00f629c7d316c472e1993494250daefbba92ddae3a6c

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[repr(usize)]
enum ArtifactDiagnosticCode {
    #[serde(rename = "artifact_directory_invalid")]
    ArtifactDirectoryInvalid,
    #[serde(rename = "artifact_directory_unavailable")]
    ArtifactDirectoryUnavailable,
    #[serde(rename = "artifact_directory_not_directory")]
    ArtifactDirectoryNotDirectory,
    #[serde(rename = "root_entry_limit_exceeded")]
    RootEntryLimitExceeded,
    #[serde(rename = "root_entry_unexpected")]
    RootEntryUnexpected,
    #[serde(rename = "boundary_name_invalid")]
    BoundaryNameInvalid,
    #[serde(rename = "result_missing")]
    ResultMissing,
    #[serde(rename = "result_symbolic_link")]
    ResultSymbolicLink,
    #[serde(rename = "result_not_regular_file")]
    ResultNotRegularFile,
    #[serde(rename = "result_unavailable")]
    ResultUnavailable,
    #[serde(rename = "result_limit_exceeded")]
    ResultLimitExceeded,
    #[serde(rename = "result_encoding_invalid")]
    ResultEncodingInvalid,
    #[serde(rename = "result_json_invalid")]
    ResultJsonInvalid,
    #[serde(rename = "result_schema_unsupported")]
    ResultSchemaUnsupported,
    #[serde(rename = "recovery_schema_unsupported")]
    RecoverySchemaUnsupported,
    #[serde(rename = "result_schema_invalid")]
    ResultSchemaInvalid,
    #[serde(rename = "exports_directory_missing")]
    ExportsDirectoryMissing,
    #[serde(rename = "exports_directory_symbolic_link")]
    ExportsDirectorySymbolicLink,
    #[serde(rename = "exports_directory_not_directory")]
    ExportsDirectoryNotDirectory,
    #[serde(rename = "exports_directory_unavailable")]
    ExportsDirectoryUnavailable,
    #[serde(rename = "export_limit_exceeded")]
    ExportLimitExceeded,
    #[serde(rename = "export_entry_invalid")]
    ExportEntryInvalid,
    #[serde(rename = "export_media_type_invalid")]
    ExportMediaTypeInvalid,
    #[serde(rename = "export_path_invalid")]
    ExportPathInvalid,
    #[serde(rename = "export_ordinal_invalid")]
    ExportOrdinalInvalid,
    #[serde(rename = "alias_metadata_mismatch")]
    AliasMetadataMismatch,
    #[serde(rename = "carrier_limit_exceeded")]
    CarrierLimitExceeded,
    #[serde(rename = "carrier_missing")]
    CarrierMissing,
    #[serde(rename = "carrier_symbolic_link")]
    CarrierSymbolicLink,
    #[serde(rename = "carrier_not_regular_file")]
    CarrierNotRegularFile,
    #[serde(rename = "carrier_unavailable")]
    CarrierUnavailable,
    #[serde(rename = "carrier_size_limit_exceeded")]
    CarrierSizeLimitExceeded,
    #[serde(rename = "carrier_total_size_limit_exceeded")]
    CarrierTotalSizeLimitExceeded,
    #[serde(rename = "carrier_size_mismatch")]
    CarrierSizeMismatch,
    #[serde(rename = "carrier_digest_mismatch")]
    CarrierDigestMismatch,
    #[serde(rename = "carrier_unreferenced")]
    CarrierUnreferenced,
    #[serde(rename = "text_encoding_invalid")]
    TextEncodingInvalid,
    #[serde(rename = "json_content_invalid")]
    JsonContentInvalid,
    #[serde(rename = "json_content_noncanonical")]
    JsonContentNoncanonical,
    #[serde(rename = "git_zero_delta_invalid")]
    GitZeroDeltaInvalid,
    #[serde(rename = "git_bundle_header_invalid")]
    GitBundleHeaderInvalid,
    #[serde(rename = "git_bundle_profile_invalid")]
    GitBundleProfileInvalid,
    #[serde(rename = "git_pack_invalid")]
    GitPackInvalid,
    #[serde(rename = "git_pack_checksum_mismatch")]
    GitPackChecksumMismatch,
    #[serde(rename = "git_content_invalid")]
    GitContentInvalid,
    #[serde(rename = "git_structure_limit_exceeded")]
    GitStructureLimitExceeded,
    #[serde(rename = "diagnostic_limit_exceeded")]
    DiagnosticLimitExceeded,
}

impl ArtifactDiagnosticCode {
    fn as_str(self) -> &'static str {
        match self {
            Self::ArtifactDirectoryInvalid => "artifact_directory_invalid",
            Self::ArtifactDirectoryUnavailable => "artifact_directory_unavailable",
            Self::ArtifactDirectoryNotDirectory => "artifact_directory_not_directory",
            Self::RootEntryLimitExceeded => "root_entry_limit_exceeded",
            Self::RootEntryUnexpected => "root_entry_unexpected",
            Self::BoundaryNameInvalid => "boundary_name_invalid",
            Self::ResultMissing => "result_missing",
            Self::ResultSymbolicLink => "result_symbolic_link",
            Self::ResultNotRegularFile => "result_not_regular_file",
            Self::ResultUnavailable => "result_unavailable",
            Self::ResultLimitExceeded => "result_limit_exceeded",
            Self::ResultEncodingInvalid => "result_encoding_invalid",
            Self::ResultJsonInvalid => "result_json_invalid",
            Self::ResultSchemaUnsupported => "result_schema_unsupported",
            Self::RecoverySchemaUnsupported => "recovery_schema_unsupported",
            Self::ResultSchemaInvalid => "result_schema_invalid",
            Self::ExportsDirectoryMissing => "exports_directory_missing",
            Self::ExportsDirectorySymbolicLink => "exports_directory_symbolic_link",
            Self::ExportsDirectoryNotDirectory => "exports_directory_not_directory",
            Self::ExportsDirectoryUnavailable => "exports_directory_unavailable",
            Self::ExportLimitExceeded => "export_limit_exceeded",
            Self::ExportEntryInvalid => "export_entry_invalid",
            Self::ExportMediaTypeInvalid => "export_media_type_invalid",
            Self::ExportPathInvalid => "export_path_invalid",
            Self::ExportOrdinalInvalid => "export_ordinal_invalid",
            Self::AliasMetadataMismatch => "alias_metadata_mismatch",
            Self::CarrierLimitExceeded => "carrier_limit_exceeded",
            Self::CarrierMissing => "carrier_missing",
            Self::CarrierSymbolicLink => "carrier_symbolic_link",
            Self::CarrierNotRegularFile => "carrier_not_regular_file",
            Self::CarrierUnavailable => "carrier_unavailable",
            Self::CarrierSizeLimitExceeded => "carrier_size_limit_exceeded",
            Self::CarrierTotalSizeLimitExceeded => "carrier_total_size_limit_exceeded",
            Self::CarrierSizeMismatch => "carrier_size_mismatch",
            Self::CarrierDigestMismatch => "carrier_digest_mismatch",
            Self::CarrierUnreferenced => "carrier_unreferenced",
            Self::TextEncodingInvalid => "text_encoding_invalid",
            Self::JsonContentInvalid => "json_content_invalid",
            Self::JsonContentNoncanonical => "json_content_noncanonical",
            Self::GitZeroDeltaInvalid => "git_zero_delta_invalid",
            Self::GitBundleHeaderInvalid => "git_bundle_header_invalid",
            Self::GitBundleProfileInvalid => "git_bundle_profile_invalid",
            Self::GitPackInvalid => "git_pack_invalid",
            Self::GitPackChecksumMismatch => "git_pack_checksum_mismatch",
            Self::GitContentInvalid => "git_content_invalid",
            Self::GitStructureLimitExceeded => "git_structure_limit_exceeded",
            Self::DiagnosticLimitExceeded => "diagnostic_limit_exceeded",
        }
    }

    const fn rank(self) -> usize {
        self as usize
    }
}
