[package]
name = "scherzo-cloud-support"
version = "0.0.0-dev"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
getrandom.workspace = true
jsonschema.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
