// Code generated by scripts/generate-runner-protocol; DO NOT EDIT.
// Canonical schema SHA-256: 33f3743f584c1d5d33cb384e0d4b9d7e1dff6906811339cfa05dc62a38d69ace
// jscpd:ignore-start -- cargo-typify output intentionally repeats validation code.

#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`AssignmentId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^asn_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct AssignmentId(::std::string::String);
impl ::std::ops::Deref for AssignmentId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<AssignmentId> for ::std::string::String {
    fn from(value: AssignmentId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for AssignmentId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^asn_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^asn_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for AssignmentId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for AssignmentId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AssignmentId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for AssignmentId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`BootId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^rbt_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct BootId(::std::string::String);
impl ::std::ops::Deref for BootId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<BootId> for ::std::string::String {
    fn from(value: BootId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for BootId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^rbt_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^rbt_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for BootId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for BootId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for BootId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for BootId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`CloudAssignmentOffer`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"direction\","]
#[doc = "    \"messageId\","]
#[doc = "    \"payload\","]
#[doc = "    \"payloadVersion\","]
#[doc = "    \"protocolVersion\","]
#[doc = "    \"sentAt\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"direction\": {"]
#[doc = "      \"const\": \"cloud_to_runner\""]
#[doc = "    },"]
#[doc = "    \"messageId\": {"]
#[doc = "      \"$ref\": \"#/$defs/cloudMessageId\""]
#[doc = "    },"]
#[doc = "    \"payload\": {"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"assignmentId\","]
#[doc = "        \"effectId\","]
#[doc = "        \"leaseExpiresAt\","]
#[doc = "        \"runId\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"assignmentId\": {"]
#[doc = "          \"$ref\": \"#/$defs/assignmentId\""]
#[doc = "        },"]
#[doc = "        \"effectId\": {"]
#[doc = "          \"$ref\": \"#/$defs/effectId\""]
#[doc = "        },"]
#[doc = "        \"leaseExpiresAt\": {"]
#[doc = "          \"$ref\": \"#/$defs/utcTimestamp\""]
#[doc = "        },"]
#[doc = "        \"runId\": {"]
#[doc = "          \"$ref\": \"#/$defs/runId\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"payloadVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"protocolVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"sentAt\": {"]
#[doc = "      \"$ref\": \"#/$defs/utcTimestamp\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"const\": \"assignment_offer\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CloudAssignmentOffer {
    pub direction: ::serde_json::Value,
    #[serde(rename = "messageId")]
    pub message_id: CloudMessageId,
    pub payload: CloudAssignmentOfferPayload,
    #[serde(rename = "payloadVersion")]
    pub payload_version: ::serde_json::Value,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: ::serde_json::Value,
    #[serde(rename = "sentAt")]
    pub sent_at: UtcTimestamp,
    #[serde(rename = "type")]
    pub type_: ::serde_json::Value,
}
#[doc = "`CloudAssignmentOfferPayload`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"assignmentId\","]
#[doc = "    \"effectId\","]
#[doc = "    \"leaseExpiresAt\","]
#[doc = "    \"runId\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"assignmentId\": {"]
#[doc = "      \"$ref\": \"#/$defs/assignmentId\""]
#[doc = "    },"]
#[doc = "    \"effectId\": {"]
#[doc = "      \"$ref\": \"#/$defs/effectId\""]
#[doc = "    },"]
#[doc = "    \"leaseExpiresAt\": {"]
#[doc = "      \"$ref\": \"#/$defs/utcTimestamp\""]
#[doc = "    },"]
#[doc = "    \"runId\": {"]
#[doc = "      \"$ref\": \"#/$defs/runId\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CloudAssignmentOfferPayload {
    #[serde(rename = "assignmentId")]
    pub assignment_id: AssignmentId,
    #[serde(rename = "effectId")]
    pub effect_id: EffectId,
    #[serde(rename = "leaseExpiresAt")]
    pub lease_expires_at: UtcTimestamp,
    #[serde(rename = "runId")]
    pub run_id: RunId,
}
#[doc = "`CloudMessageId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^cmsg_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct CloudMessageId(::std::string::String);
impl ::std::ops::Deref for CloudMessageId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<CloudMessageId> for ::std::string::String {
    fn from(value: CloudMessageId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for CloudMessageId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^cmsg_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^cmsg_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for CloudMessageId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for CloudMessageId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for CloudMessageId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for CloudMessageId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`CloudObservationAck`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"direction\","]
#[doc = "    \"messageId\","]
#[doc = "    \"payload\","]
#[doc = "    \"payloadVersion\","]
#[doc = "    \"protocolVersion\","]
#[doc = "    \"sentAt\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"direction\": {"]
#[doc = "      \"const\": \"cloud_to_runner\""]
#[doc = "    },"]
#[doc = "    \"messageId\": {"]
#[doc = "      \"$ref\": \"#/$defs/cloudMessageId\""]
#[doc = "    },"]
#[doc = "    \"payload\": {"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"acknowledgedMessageId\","]
#[doc = "        \"acknowledgedSequence\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"acknowledgedMessageId\": {"]
#[doc = "          \"$ref\": \"#/$defs/runnerMessageId\""]
#[doc = "        },"]
#[doc = "        \"acknowledgedSequence\": {"]
#[doc = "          \"$ref\": \"#/$defs/sequence\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"payloadVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"protocolVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"sentAt\": {"]
#[doc = "      \"$ref\": \"#/$defs/utcTimestamp\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"const\": \"observation_ack\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CloudObservationAck {
    pub direction: ::serde_json::Value,
    #[serde(rename = "messageId")]
    pub message_id: CloudMessageId,
    pub payload: CloudObservationAckPayload,
    #[serde(rename = "payloadVersion")]
    pub payload_version: ::serde_json::Value,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: ::serde_json::Value,
    #[serde(rename = "sentAt")]
    pub sent_at: UtcTimestamp,
    #[serde(rename = "type")]
    pub type_: ::serde_json::Value,
}
#[doc = "`CloudObservationAckPayload`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"acknowledgedMessageId\","]
#[doc = "    \"acknowledgedSequence\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"acknowledgedMessageId\": {"]
#[doc = "      \"$ref\": \"#/$defs/runnerMessageId\""]
#[doc = "    },"]
#[doc = "    \"acknowledgedSequence\": {"]
#[doc = "      \"$ref\": \"#/$defs/sequence\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CloudObservationAckPayload {
    #[serde(rename = "acknowledgedMessageId")]
    pub acknowledged_message_id: RunnerMessageId,
    #[serde(rename = "acknowledgedSequence")]
    pub acknowledged_sequence: Sequence,
}
#[doc = "`CloudWelcome`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"direction\","]
#[doc = "    \"messageId\","]
#[doc = "    \"payload\","]
#[doc = "    \"payloadVersion\","]
#[doc = "    \"protocolVersion\","]
#[doc = "    \"sentAt\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"direction\": {"]
#[doc = "      \"const\": \"cloud_to_runner\""]
#[doc = "    },"]
#[doc = "    \"messageId\": {"]
#[doc = "      \"$ref\": \"#/$defs/cloudMessageId\""]
#[doc = "    },"]
#[doc = "    \"payload\": {"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"pingIntervalSeconds\","]
#[doc = "        \"pongTimeoutSeconds\","]
#[doc = "        \"sessionId\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"pingIntervalSeconds\": {"]
#[doc = "          \"type\": \"integer\","]
#[doc = "          \"maximum\": 60.0,"]
#[doc = "          \"minimum\": 1.0"]
#[doc = "        },"]
#[doc = "        \"pongTimeoutSeconds\": {"]
#[doc = "          \"type\": \"integer\","]
#[doc = "          \"maximum\": 300.0,"]
#[doc = "          \"minimum\": 2.0"]
#[doc = "        },"]
#[doc = "        \"sessionId\": {"]
#[doc = "          \"$ref\": \"#/$defs/sessionId\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"payloadVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"protocolVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"sentAt\": {"]
#[doc = "      \"$ref\": \"#/$defs/utcTimestamp\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"const\": \"welcome\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CloudWelcome {
    pub direction: ::serde_json::Value,
    #[serde(rename = "messageId")]
    pub message_id: CloudMessageId,
    pub payload: CloudWelcomePayload,
    #[serde(rename = "payloadVersion")]
    pub payload_version: ::serde_json::Value,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: ::serde_json::Value,
    #[serde(rename = "sentAt")]
    pub sent_at: UtcTimestamp,
    #[serde(rename = "type")]
    pub type_: ::serde_json::Value,
}
#[doc = "`CloudWelcomePayload`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"pingIntervalSeconds\","]
#[doc = "    \"pongTimeoutSeconds\","]
#[doc = "    \"sessionId\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"pingIntervalSeconds\": {"]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"maximum\": 60.0,"]
#[doc = "      \"minimum\": 1.0"]
#[doc = "    },"]
#[doc = "    \"pongTimeoutSeconds\": {"]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"maximum\": 300.0,"]
#[doc = "      \"minimum\": 2.0"]
#[doc = "    },"]
#[doc = "    \"sessionId\": {"]
#[doc = "      \"$ref\": \"#/$defs/sessionId\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CloudWelcomePayload {
    #[serde(rename = "pingIntervalSeconds")]
    pub ping_interval_seconds: ::std::num::NonZeroU64,
    #[serde(rename = "pongTimeoutSeconds")]
    pub pong_timeout_seconds: i64,
    #[serde(rename = "sessionId")]
    pub session_id: SessionId,
}
#[doc = "`EffectId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^eff_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct EffectId(::std::string::String);
impl ::std::ops::Deref for EffectId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<EffectId> for ::std::string::String {
    fn from(value: EffectId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for EffectId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^eff_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^eff_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for EffectId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for EffectId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for EffectId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for EffectId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`RunId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^run_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct RunId(::std::string::String);
impl ::std::ops::Deref for RunId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<RunId> for ::std::string::String {
    fn from(value: RunId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for RunId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^run_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^run_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for RunId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for RunId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RunId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for RunId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`RunnerEffectAcknowledged`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"bootId\","]
#[doc = "    \"direction\","]
#[doc = "    \"messageId\","]
#[doc = "    \"payload\","]
#[doc = "    \"payloadVersion\","]
#[doc = "    \"protocolVersion\","]
#[doc = "    \"runnerId\","]
#[doc = "    \"sentAt\","]
#[doc = "    \"sequence\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"bootId\": {"]
#[doc = "      \"$ref\": \"#/$defs/bootId\""]
#[doc = "    },"]
#[doc = "    \"direction\": {"]
#[doc = "      \"const\": \"runner_to_cloud\""]
#[doc = "    },"]
#[doc = "    \"messageId\": {"]
#[doc = "      \"$ref\": \"#/$defs/runnerMessageId\""]
#[doc = "    },"]
#[doc = "    \"payload\": {"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"effectId\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"effectId\": {"]
#[doc = "          \"$ref\": \"#/$defs/effectId\""]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"payloadVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"protocolVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"runnerId\": {"]
#[doc = "      \"$ref\": \"#/$defs/runnerId\""]
#[doc = "    },"]
#[doc = "    \"sentAt\": {"]
#[doc = "      \"$ref\": \"#/$defs/utcTimestamp\""]
#[doc = "    },"]
#[doc = "    \"sequence\": {"]
#[doc = "      \"$ref\": \"#/$defs/sequence\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"const\": \"effect_acknowledged\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RunnerEffectAcknowledged {
    #[serde(rename = "bootId")]
    pub boot_id: BootId,
    pub direction: ::serde_json::Value,
    #[serde(rename = "messageId")]
    pub message_id: RunnerMessageId,
    pub payload: RunnerEffectAcknowledgedPayload,
    #[serde(rename = "payloadVersion")]
    pub payload_version: ::serde_json::Value,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: ::serde_json::Value,
    #[serde(rename = "runnerId")]
    pub runner_id: RunnerId,
    #[serde(rename = "sentAt")]
    pub sent_at: UtcTimestamp,
    pub sequence: Sequence,
    #[serde(rename = "type")]
    pub type_: ::serde_json::Value,
}
#[doc = "`RunnerEffectAcknowledgedPayload`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"effectId\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"effectId\": {"]
#[doc = "      \"$ref\": \"#/$defs/effectId\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RunnerEffectAcknowledgedPayload {
    #[serde(rename = "effectId")]
    pub effect_id: EffectId,
}
#[doc = "`RunnerHello`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"bootId\","]
#[doc = "    \"direction\","]
#[doc = "    \"messageId\","]
#[doc = "    \"payload\","]
#[doc = "    \"payloadVersion\","]
#[doc = "    \"protocolVersion\","]
#[doc = "    \"runnerId\","]
#[doc = "    \"sentAt\","]
#[doc = "    \"sequence\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"bootId\": {"]
#[doc = "      \"$ref\": \"#/$defs/bootId\""]
#[doc = "    },"]
#[doc = "    \"direction\": {"]
#[doc = "      \"const\": \"runner_to_cloud\""]
#[doc = "    },"]
#[doc = "    \"messageId\": {"]
#[doc = "      \"$ref\": \"#/$defs/runnerMessageId\""]
#[doc = "    },"]
#[doc = "    \"payload\": {"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"maxConcurrentRuns\","]
#[doc = "        \"runnerVersion\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"maxConcurrentRuns\": {"]
#[doc = "          \"type\": \"integer\","]
#[doc = "          \"maximum\": 2147483647.0,"]
#[doc = "          \"minimum\": 1.0"]
#[doc = "        },"]
#[doc = "        \"runnerVersion\": {"]
#[doc = "          \"type\": \"string\","]
#[doc = "          \"maxLength\": 128,"]
#[doc = "          \"minLength\": 1"]
#[doc = "        }"]
#[doc = "      },"]
#[doc = "      \"additionalProperties\": false"]
#[doc = "    },"]
#[doc = "    \"payloadVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"protocolVersion\": {"]
#[doc = "      \"const\": 1"]
#[doc = "    },"]
#[doc = "    \"runnerId\": {"]
#[doc = "      \"$ref\": \"#/$defs/runnerId\""]
#[doc = "    },"]
#[doc = "    \"sentAt\": {"]
#[doc = "      \"$ref\": \"#/$defs/utcTimestamp\""]
#[doc = "    },"]
#[doc = "    \"sequence\": {"]
#[doc = "      \"$ref\": \"#/$defs/sequence\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"const\": \"hello\""]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RunnerHello {
    #[serde(rename = "bootId")]
    pub boot_id: BootId,
    pub direction: ::serde_json::Value,
    #[serde(rename = "messageId")]
    pub message_id: RunnerMessageId,
    pub payload: RunnerHelloPayload,
    #[serde(rename = "payloadVersion")]
    pub payload_version: ::serde_json::Value,
    #[serde(rename = "protocolVersion")]
    pub protocol_version: ::serde_json::Value,
    #[serde(rename = "runnerId")]
    pub runner_id: RunnerId,
    #[serde(rename = "sentAt")]
    pub sent_at: UtcTimestamp,
    pub sequence: Sequence,
    #[serde(rename = "type")]
    pub type_: ::serde_json::Value,
}
#[doc = "`RunnerHelloPayload`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"maxConcurrentRuns\","]
#[doc = "    \"runnerVersion\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"maxConcurrentRuns\": {"]
#[doc = "      \"type\": \"integer\","]
#[doc = "      \"maximum\": 2147483647.0,"]
#[doc = "      \"minimum\": 1.0"]
#[doc = "    },"]
#[doc = "    \"runnerVersion\": {"]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"maxLength\": 128,"]
#[doc = "      \"minLength\": 1"]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"additionalProperties\": false"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RunnerHelloPayload {
    #[serde(rename = "maxConcurrentRuns")]
    pub max_concurrent_runs: ::std::num::NonZeroU64,
    #[serde(rename = "runnerVersion")]
    pub runner_version: RunnerHelloPayloadRunnerVersion,
}
#[doc = "`RunnerHelloPayloadRunnerVersion`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"maxLength\": 128,"]
#[doc = "  \"minLength\": 1"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct RunnerHelloPayloadRunnerVersion(::std::string::String);
impl ::std::ops::Deref for RunnerHelloPayloadRunnerVersion {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<RunnerHelloPayloadRunnerVersion> for ::std::string::String {
    fn from(value: RunnerHelloPayloadRunnerVersion) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for RunnerHelloPayloadRunnerVersion {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 128usize {
            return Err("longer than 128 characters".into());
        }
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for RunnerHelloPayloadRunnerVersion {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for RunnerHelloPayloadRunnerVersion {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RunnerHelloPayloadRunnerVersion {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for RunnerHelloPayloadRunnerVersion {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`RunnerId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^rnr_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct RunnerId(::std::string::String);
impl ::std::ops::Deref for RunnerId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<RunnerId> for ::std::string::String {
    fn from(value: RunnerId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for RunnerId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^rnr_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^rnr_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for RunnerId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for RunnerId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RunnerId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for RunnerId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`RunnerMessageId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^rmsg_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct RunnerMessageId(::std::string::String);
impl ::std::ops::Deref for RunnerMessageId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<RunnerMessageId> for ::std::string::String {
    fn from(value: RunnerMessageId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for RunnerMessageId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^rmsg_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^rmsg_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for RunnerMessageId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for RunnerMessageId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RunnerMessageId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for RunnerMessageId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "Closed JSON text frames exchanged by a Scherzo runner and gateway."]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"$id\": \"https://scherzo.dev/contracts/runner-protocol-v1.schema.json\","]
#[doc = "  \"title\": \"Runner protocol version 1\","]
#[doc = "  \"description\": \"Closed JSON text frames exchanged by a Scherzo runner and gateway.\","]
#[doc = "  \"oneOf\": ["]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/$defs/RunnerHello\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/$defs/RunnerEffectAcknowledged\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/$defs/CloudWelcome\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/$defs/CloudObservationAck\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/$defs/CloudAssignmentOffer\""]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum RunnerProtocolVersion1 {
    RunnerHello(RunnerHello),
    RunnerEffectAcknowledged(RunnerEffectAcknowledged),
    CloudWelcome(CloudWelcome),
    CloudObservationAck(CloudObservationAck),
    CloudAssignmentOffer(CloudAssignmentOffer),
}
impl ::std::convert::From<RunnerHello> for RunnerProtocolVersion1 {
    fn from(value: RunnerHello) -> Self {
        Self::RunnerHello(value)
    }
}
impl ::std::convert::From<RunnerEffectAcknowledged> for RunnerProtocolVersion1 {
    fn from(value: RunnerEffectAcknowledged) -> Self {
        Self::RunnerEffectAcknowledged(value)
    }
}
impl ::std::convert::From<CloudWelcome> for RunnerProtocolVersion1 {
    fn from(value: CloudWelcome) -> Self {
        Self::CloudWelcome(value)
    }
}
impl ::std::convert::From<CloudObservationAck> for RunnerProtocolVersion1 {
    fn from(value: CloudObservationAck) -> Self {
        Self::CloudObservationAck(value)
    }
}
impl ::std::convert::From<CloudAssignmentOffer> for RunnerProtocolVersion1 {
    fn from(value: CloudAssignmentOffer) -> Self {
        Self::CloudAssignmentOffer(value)
    }
}
#[doc = "`Sequence`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"integer\","]
#[doc = "  \"maximum\": 9.223372036854776e+18,"]
#[doc = "  \"minimum\": 1.0"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct Sequence(pub ::std::num::NonZeroU64);
impl ::std::ops::Deref for Sequence {
    type Target = ::std::num::NonZeroU64;
    fn deref(&self) -> &::std::num::NonZeroU64 {
        &self.0
    }
}
impl ::std::convert::From<Sequence> for ::std::num::NonZeroU64 {
    fn from(value: Sequence) -> Self {
        value.0
    }
}
impl ::std::convert::From<::std::num::NonZeroU64> for Sequence {
    fn from(value: ::std::num::NonZeroU64) -> Self {
        Self(value)
    }
}
impl ::std::str::FromStr for Sequence {
    type Err = <::std::num::NonZeroU64 as ::std::str::FromStr>::Err;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.parse()?))
    }
}
impl ::std::convert::TryFrom<&str> for Sequence {
    type Error = <::std::num::NonZeroU64 as ::std::str::FromStr>::Err;
    fn try_from(value: &str) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<String> for Sequence {
    type Error = <::std::num::NonZeroU64 as ::std::str::FromStr>::Err;
    fn try_from(value: String) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
impl ::std::fmt::Display for Sequence {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
#[doc = "`SessionId`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^rsn_[0-7][0-9a-hjkmnp-tv-z]{25}$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SessionId(::std::string::String);
impl ::std::ops::Deref for SessionId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SessionId> for ::std::string::String {
    fn from(value: SessionId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SessionId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^rsn_[0-7][0-9a-hjkmnp-tv-z]{25}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^rsn_[0-7][0-9a-hjkmnp-tv-z]{25}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SessionId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for SessionId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SessionId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SessionId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`UtcTimestamp`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"pattern\": \"^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\\.[0-9]+)?Z$\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct UtcTimestamp(::std::string::String);
impl ::std::ops::Deref for UtcTimestamp {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<UtcTimestamp> for ::std::string::String {
    fn from(value: UtcTimestamp) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for UtcTimestamp {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(
            || {
                :: regress :: Regex :: new ("^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?Z$") . unwrap ()
            },
        );
        if PATTERN.find(value).is_none() {
            return Err ("doesn't match pattern \"^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?Z$\"" . into ()) ;
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for UtcTimestamp {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for UtcTimestamp {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for UtcTimestamp {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for UtcTimestamp {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}

// jscpd:ignore-end
